### ISSUE TITLE
t1可以用这个吗

### ISSUE THREAD

**Issue by liuyang77886** [yangxuan8282/phicomm-n1#1]
t1可以用这个吗

**Comment by yangxuan8282** [comment]
你说的是哪个镜像？应该是可以的，换成 t1 的 dtb 就行，我没有设备，没法测试

**Comment by liuyang77886** [comment]
问题1meson-gxl-s905d-phicomm-n1.dtb这个文件能用于t1吗
问题2你说“换成t1的dtb”，我应该通过什么方式知道选择哪个呢，是meson-gxl-s805x-p241.dtb？meson-gxl-s905d-p230.dtb？meson-gxl-s905d-p231.dtb？这3个中的其中1个吗？

**Comment by liuyang77886** [comment]
问题3，meson-gxl-s905d-phicomm-n1.dtb这个是解决了一些缺陷比如说文件传输断开问题。如果我用meson-gxl-s905d-p？？？.dtb其中1个，就存在以前的问题了。有资料解决吗

**Comment by yangxuan8282** [comment]
不能，这个 dtb 就是 N1 适用的， T1 肯定不能用，平台都不同
