### ISSUE TITLE
希望给出各系统密码

### ISSUE THREAD

**Issue by lhx11187** [yangxuan8282/phicomm-n1#10]
下载了debian系统，没找到密码在哪，试过1234不正确

**Comment by yangxuan8282** [comment]
用户名n1
密码phicomm

**Comment by lhx11187** [comment]
> 用户名n1
> 密码phicomm

感谢，我翻遍恩山没找到，能试的都试了，再说没root用户？再次感谢回复

**Comment by yangxuan8282** [comment]
@lhx11187 
debian 镜像是用这个脚本生成的： https://github.com/yangxuan8282/gen-rpi_os/blob/master/gen-debian_n1.sh
有 root 用户，只不过当时没设置 root 密码，可以自己设
我的镜像除了 LibreELEC 其它 sudo 用户都是 n1，密码是 phicomm ，如果设置了 root 用户密码那就是 toor

**Comment by qkqpttgf** [comment]
CentOS-7-aarch64-n1-7.5.1804_4.18.7_20180922.zip
这个用n1/phicomm能登录，但没找到root密码，toor不对。找到了，root/centos。
