### ISSUE TITLE
大佬能把这个CoreELEC-Sx05re适配N1吗

### ISSUE THREAD

**Issue by leeairw** [yangxuan8282/phicomm-n1#11]
https://github.com/shantigilbert/CoreELEC
水平有限，研究了几天只能运行到初始化完毕，自动重启后就卡在LOGO界面不动了。

**Comment by yangxuan8282** [comment]
已经有人做了，wiki里有链接： https://github.com/yangxuan8282/phicomm-n1/wiki/OS

**Comment by leeairw** [comment]
编译过的程序确认有人已经发出来了。但是源码并不能直接编译成N1可用的。大佬能不能做fork一个可以源码编译出来适配N1的

**Comment by leeairw** [comment]
大佬回复这么快太高兴了。都忘了感谢~抱歉抱歉。感谢大佬这么快回复。

**Comment by yangxuan8282** [comment]
这个建议还是直接问放出系统的人吧
