### ISSUE TITLE
请问哪个版本的System Load负载较低？

### ISSUE THREAD

**Issue by ZidongY** [yangxuan8282/phicomm-n1#16]
最近刚入手一个N1，还在研究中。
昨天使用了你的最新的两个dtb，系统刷的是“Armbian_5.67_Aml-s9xxx_Debian_stretch_default_4.19.7_20181218.img”
目前使用正常，就是想你文中所说的平均负载在2左右。想咨询下那种内核、版本的搭配系统负载最低、最稳定？

**Comment by yangxuan8282** [comment]
4.18的内核加上 https://github.com/yangxuan8282/phicomm-n1/releases/download/dtb/meson-gxl-s905d-phicomm-n1.dtb
