### ISSUE TITLE
可以使用pxe或者tftp引导一个完整的debian吗？

### ISSUE THREAD

**Issue by charleyzhu** [yangxuan8282/phicomm-n1#2]
如题吗，可以使用pxe或者tftp引导系统启动，把N1当做无盘工作站来使用吗？

**Comment by yangxuan8282** [comment]
pxe 目录下的文件就已经可引导完整的 debian 了，目前还要插优盘的原因只是存放 u-boot 文件，如果把这部分文件写入 emmc 就可以实现完全 diskless 了，但我没有研究过 emmc 相关的，如果有需要自行尝试，自己承担风险

**Comment by charleyzhu** [comment]
谢谢，我试试看
