### ISSUE TITLE
编译新内核 uInitrd 文件不知道该怎么生成 ，请指教下；

### ISSUE THREAD

**Issue by Hnmtc** [yangxuan8282/phicomm-n1#22]
编译新内核 uInitrd 文件不知道该怎么生成 ，请指教下；

**Comment by yangxuan8282** [comment]
https://github.com/yangxuan8282/gen-rpi_os/blob/04634129c5e5db65e79eeb191bbdeb8286fb0690/gen-alpine_n1.sh#L255
