### ISSUE TITLE
n1的u-boot.bin哪里来的？

### ISSUE THREAD

**Issue by RuralHunter** [yangxuan8282/phicomm-n1#25]
老大，你的n1的u-boot.bin是哪里来的？是自己编译出来的还是从n1里弄出来的？

**Comment by laris** [comment]
请问，下面四个uboot有什么区别？

123是wiki中提到的，vim2.01/2和不带_vim有什么区别？
4 带_pxe是 pxe目录中的 https://github.com/yangxuan8282/phicomm-n1/tree/master/pxe/usb

https://github.com/yangxuan8282/phicomm-n1/wiki/%E8%87%AA%E5%B7%B1%E5%88%B6%E4%BD%9C-N1-%E7%9A%84-Linux-%E9%95%9C%E5%83%8F

`local url="https://github.com/yangxuan8282/phicomm-n1/releases/download/20180917/u-boot.bin"`

https://github.com/yangxuan8282/phicomm-n1/releases/tag/20180917

```
MD5 (u-boot.bin) = 5cf8b1bcf584af5a73c8940753e56e8a
MD5 (u-boot.bin_vim2.01) = 1fc5a527999c5411c4b981ee6b8115d8
MD5 (u-boot.bin_vim2.02) = 3c83d77f5224adf13b5abf31293eb6f5
MD5 (u-boot_pxe.bin) = 5d921bf1d57baf081a7b2e969d7f70a5
```

**Comment by RuralHunter** [comment]
我研究了一下，实际上u-boot并不需要。系统mmc自带了，只要降级了u-boot就支持从u盘启动。
