### ISSUE TITLE
求debian的emmc脚本!

### ISSUE THREAD

**Issue by kevinshane** [yangxuan8282/phicomm-n1#7]
大神好, 你家的Debian也好小巧哦, 希望能加入emmc脚本支持, 非常感谢!

**Comment by yangxuan8282** [comment]
之前发的安装 alpine 到 emmc 的脚本你那能启动吗

**Comment by kevinshane** [comment]
启动不了(一直黑屏), 不过由于我需要运行到一些java程序, 而alpine对java支持不是很好, 所以放弃alpine了..
然后就发现你的debian也好小, 300多MB, 比臃肿的armbian随便就1.5g好太多了..故求个emmc :)
